# Copyright 2023 The Regents of the University of California
# released under BSD 3-Clause License
# author: Kevin Laeufer <laeufer@berkeley.edu>

[package]
name = "waveform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
clap = { version = "4.4.6", features = ["derive"] }
fst-native = "0.6.0"
leb128 = "0.2.5"
lz4_flex = "0.11.1"
rayon = "1.8.0"
smallvec = "1.11.1"
string-interner = { version = "0.14.0", features = ["std", "inline-more", "backends"] }
