# Copyright 2023-2024 The Regents of the University of California
# released under BSD 3-Clause License
# author: Kevin Laeufer <laeufer@berkeley.edu>

[package]
name = "wellen"
version = "0.9.10"
edition = "2021"
# we require the `div_ceil` method on integers
rust-version="1.73.0"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "Fast VCD and FST library for waveform viewers written in Rust."
repository = "https://github.com/ekiwi/wellen"
license = "BSD-3-Clause"
include = ["Cargo.toml", "LICENSE", "src/", "benches/"]
keywords = ["vcd", "fst", "waveform", "wavedump"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
fst-native = "0.8.1"
leb128 = "0.2.5"
lz4_flex = "0.11.1"
memmap2 = "0.9.0"
rayon = "1.8.0"
num_enum = "0.7.1"
thiserror = "1.0.56"
serde = { version = "1.0.197", features = ["derive"], optional = true }

[dev-dependencies]
itertools = "0.12.1"
vcd = "0.7.0"
clap = { version = "4.4.6", features = ["derive"] }
criterion = "0.5"
indicatif = "0.17.8"
proptest = "1.4.0"

[profile.release]
debug = true

[[bench]]
name = "wavemem"
harness = false

[features]
# makes internal functions public for benchmarking
benchmark = []
serde1 = ["dep:serde"]
